{% set version = "0.11.0" %}

package:
  name: reproject
  version: {{ version }}

source:
  fn: reproject-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/reproject/reproject-{{ version }}.tar.gz
  md5: d0714c4f05dfe6bad7ea61c925888df6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - pip
    - setuptools
    - setuptools-scm
    - cython
    - extension-helpers
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - astropy >=4.0
    - astropy-healpix >=0.6
    - scipy >=1.3
    - dask >=2020
    - cloudpickle
    - zarr
    - fsspec

test:
  requires:
    - pytest-astropy
  imports:
    - reproject
    - reproject.healpix
    - reproject.interpolation
    - reproject.spherical_intersect
  commands:
    - python -c "import reproject"

about:
  home: http://reproject.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The reproject package implements image reprojection (resampling) methods for astronomical data.

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - mwcraig
    - bsipocz
    - Cadair
