# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_NPY=110  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=110  CONDA_PY=34
    - CONDA_NPY=111  CONDA_PY=34
    - CONDA_NPY=110  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GNHo8R8npfy3QXIv2kwdHV9stx0crP+xgR/VUz0pi/2EPVttSpo1ZsQUtzxzHWm+9+cAWoYSeYC/qR6WLGfPlcy6QLw73wwdMpWqc93WfJnlxqwY+b8Ey6+fQmQJ1cNlU9wTbs10PTeyv82mhk/aWrCaMT9XX8np6F13pn6q0+86GM1K+TXks8KhDe37S41bUA8dhaIolU83hv9OyMJZ9lRQMGJ6MnY7IRLp8BokcIkozNuRfPUBrAPdfg4xS46hnDJRGtFmvVgdHCuDcQQXIoUL/HBw5TaiHbgRB8ltc0RdSApDvPVnlPTR6BnQatxI4DXGhS/F+EbA37E8SHb2UCHRtvsGg+jGk5Mepjn7i+wKTFUvF9FlAlQElMPSAccyUi0izTcZpqMs/bvhcC/jzTXLq8SnJmmmdHYUYb+Z+i1r+0r/PLgC6wHlKqSLndlsEOjODDxfNtZ2ZOvOAcJK3YyW+TbsDjOSlUbKlJO4swD24KjiaGjvOOY81s9ds/epY1XugCbRzkqZch6E2C/77yEHSWoqq1/DdxcR6CWYftY32LIfUx5W5tYzEjPDKIMfD/G+6cq9bJ7en35KuhQjL9Nw7+3/CEpirEz/QtQgF77xAPAemhd3nRyXdpWAgoG7VcsE2CI3Y5XsBnUV58JSnb8DPt60wF5klklfedsX5S4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
