travis:
  secure:
    BINSTAR_TOKEN: GNHo8R8npfy3QXIv2kwdHV9stx0crP+xgR/VUz0pi/2EPVttSpo1ZsQUtzxzHWm+9+cAWoYSeYC/qR6WLGfPlcy6QLw73wwdMpWqc93WfJnlxqwY+b8Ey6+fQmQJ1cNlU9wTbs10PTeyv82mhk/aWrCaMT9XX8np6F13pn6q0+86GM1K+TXks8KhDe37S41bUA8dhaIolU83hv9OyMJZ9lRQMGJ6MnY7IRLp8BokcIkozNuRfPUBrAPdfg4xS46hnDJRGtFmvVgdHCuDcQQXIoUL/HBw5TaiHbgRB8ltc0RdSApDvPVnlPTR6BnQatxI4DXGhS/F+EbA37E8SHb2UCHRtvsGg+jGk5Mepjn7i+wKTFUvF9FlAlQElMPSAccyUi0izTcZpqMs/bvhcC/jzTXLq8SnJmmmdHYUYb+Z+i1r+0r/PLgC6wHlKqSLndlsEOjODDxfNtZ2ZOvOAcJK3YyW+TbsDjOSlUbKlJO4swD24KjiaGjvOOY81s9ds/epY1XugCbRzkqZch6E2C/77yEHSWoqq1/DdxcR6CWYftY32LIfUx5W5tYzEjPDKIMfD/G+6cq9bJ7en35KuhQjL9Nw7+3/CEpirEz/QtQgF77xAPAemhd3nRyXdpWAgoG7VcsE2CI3Y5XsBnUV58JSnb8DPt60wF5klklfedsX5S4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
