travis:
  secure:
    BINSTAR_TOKEN: Unzxqy/uhG7WMNORpiTg5+B2T92IK/hCoQ11SNaFbrBYyOxuwdDnoB4+SGHKXV808nQ/We8x6Lt6mlDhzayrHBOeH6BBeFr7cKkoIIlv2bxpmlwfeVTzErQ5JiqZ2IYVV9Wx9tPCFlWdZ8ysGuiga/VHZ68TB18AOMtLFoZlKS01L1I5bF24I4kVh3Hk5a1M7Q7Jpc/mwF/38Axq9jmAM5M1KDsv4gY1emASH0VcoZXcnmCjmTsUgjWhCy7TIBber2Ujr3ICoesXlbIi3vw8apwAe/8tIeMpE+lYJCcp8hx9hKNV/c/0em0+XkmHm7sBulQTfdi1ThxO5Qd5YNgX6QzAaVBZyxMuTV2EzCuMNlOowGpOtfmXYfgaVsnqeUa5SHOnY/Eg2EguWdDxmFYnqVTIBQSNFF9RTNOsAB06tnLejmEp0wCmDADpEqvTQklNxnE5ZboveeQanEflQvydTTjpP0hF5y0Ygy4tRXfA18h2GOfLITfW33C7dDcaYz4nfD3+twmu6ui2oJtbsC2j5do3ROFncgSnnF1dsEoDJy1YjLmcLvhCCbXwCJni3IM4vWQNfCTrR/rqF4zELf6d3t11sQuthYlJjUVjpXm6497dt3E0BwtpPPEUFT72T7BWxmtjLsJpvWyFk7TzC87ZJOCTMBq1850l9t0zm3FKI6Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
